"""
Email alert module
Handles sending security alerts via email
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
import pandas as pd
from src.config import Config


def generate_alert_html(df_high_risk: pd.DataFrame, target_name: str) -> str:
    """
    Generate HTML content for email alert
    
    Args:
        df_high_risk (pd.DataFrame): DataFrame with high-risk entries
        target_name (str): Name of the scan target
        
    Returns:
        str: HTML formatted alert message
    """
    # Create HTML table
    table_html = df_high_risk[["ip", "port", "service", "vt_reputation", "risk_score", "severity"]].to_html(index=False)
    
    html = f"""
    <html>
        <body style="font-family: Arial, sans-serif;">
            <div style="background-color: #f8f9fa; padding: 20px; border-radius: 5px;">
                <h2 style="color: #d32f2f;">🚨 CyberScan Pro Security Alert</h2>
                
                <p><strong>Target:</strong> {target_name}</p>
                <p><strong>Scan Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Alert Count:</strong> {len(df_high_risk)} high/critical risk entries detected</p>
                
                <h3 style="color: #d32f2f;">High Risk Findings</h3>
                {table_html}
                
                <hr>
                <p style="color: #666; font-size: 12px;">
                    <em>Automatically generated by CyberScan Pro. Do not reply to this email.</em>
                </p>
            </div>
        </body>
    </html>
    """
    
    return html


def send_email_alert(df: pd.DataFrame, target_name: str) -> str:
    """
    Send email alert for high-risk vulnerabilities
    
    Args:
        df (pd.DataFrame): DataFrame with scan results
        target_name (str): Name of the scan target
        
    Returns:
        str: Status message
    """
    # Filter high-risk entries
    high_risk = df[df["severity"].isin(["High", "Critical"])]
    
    if high_risk.empty:
        print("ℹ️ No high-risk vulnerabilities - email not sent")
        return "No high-risk findings"
    
    # Validate email configuration
    if not all([Config.SENDER_EMAIL, Config.APP_PASSWORD, Config.RECEIVER_EMAIL]):
        print("⚠️ Email configuration incomplete - cannot send alert")
        return "Email configuration incomplete"
    
    try:
        # Create email message
        msg = MIMEMultipart("alternative")
        msg["From"] = Config.SENDER_EMAIL
        msg["To"] = Config.RECEIVER_EMAIL
        msg["Subject"] = f"[SECURITY ALERT] High-risk vulnerabilities detected on {target_name}"
        
        # Generate HTML content
        html_content = generate_alert_html(high_risk, target_name)
        msg.attach(MIMEText(html_content, "html"))
        
        # Send email
        server = smtplib.SMTP(Config.SMTP_SERVER, Config.SMTP_PORT)
        server.starttls()
        server.login(Config.SENDER_EMAIL, Config.APP_PASSWORD)
        server.sendmail(Config.SENDER_EMAIL, Config.RECEIVER_EMAIL, msg.as_string())
        server.quit()
        
        print(f"✉️ Alert email sent to {Config.RECEIVER_EMAIL}")
        return f"Email sent successfully with {len(high_risk)} alert(s)"
    
    except smtplib.SMTPException as e:
        print(f"✗ SMTP error sending email: {e}")
        return f"Failed to send email: {e}"
    except Exception as e:
        print(f"✗ Error sending email: {e}")
        return f"Error sending email: {e}"
